# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    environment:
      - DATABASE_URL: "postgres://postgres@localhost:5432/myapp"
    docker:
      # specify the version you desire here
      - image: circleci/node:9.4.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
      - image: circleci/postgres
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_DB=myapp

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          command: yarn test --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: junit/test-results.xml
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - run:
          command: |
            mkdir -p ~/reports
            yarn lint --format junit --output-file ~/reports/eslint.xml src/** test/**
          when: always
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
